name: Testes de API

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  teste-de-api-com-serverest-local-em-docker:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
    - name: Setup do Node.js
      uses: actions/setup-node@v2.1.1
    - name: Instalar as dependências do projeto
      run: npm ci
    - name: Executar o ServeRest localmente com Docker
      run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest:latest
    - name: Executar os testes de API
      run: npm test
      
  teste-de-api-em-serverest-dev:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
    - name: Setup do Node.js
      uses: actions/setup-node@v2.1.1
    - name: Instalar as dependências do projeto
      run: npm ci
    - name: Executar os testes de API
      run: npm run test:prod
       - name: mostra as pastas
      run: ls -la
    - name: Collect Allure files and generate allure-report folder
      run: |
        allure generate ./allure-results -o allure-report/
    - name: Publishing Allure artifact to GitHub Actions
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # default: gh-pages
        publish_dir: allure-report
        destination_dir: allure-report
